# Generated by Django 3.2.6 on 2021-10-08 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0002_auto_20211008_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifincidentesusuarios',
            options={'ordering': ['usuario_id'], 'verbose_name': 'Notificacion de incidencia', 'verbose_name_plural': 'Notificaciones de incidencia'},
        ),
        migrations.AlterModelOptions(
            name='registronoexitosocliente',
            options={'ordering': ['fechaSuceso'], 'verbose_name': 'Registro no Exitoso de Cliente', 'verbose_name_plural': 'Registros no Exitosos de Clientes'},
        ),
        migrations.AlterField(
            model_name='registronoexitosocliente',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 16, 47, 3, 150636), null=True),
        ),
        migrations.AlterField(
            model_name='registronoexitosocliente',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 16, 47, 3, 150272)),
        ),
        migrations.AlterModelTable(
            name='notifincidentesusuarios',
            table='usuarios_notifIncidencias',
        ),
        migrations.AlterModelTable(
            name='registronoexitosocliente',
            table='bot_log_registroNoExitosoCliente',
        ),
    ]
