# Generated by Django 3.2.6 on 2021-10-10 23:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_telegram', '0008_auto_20211009_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroBotIncidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSuceso', models.DateTimeField(default=datetime.datetime(2021, 10, 10, 20, 31, 54, 641842))),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fechaRevision', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 10, 20, 31, 54, 642203), null=True)),
                ('revisadoPor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que revis√≥ el inconveniente')),
            ],
            options={
                'verbose_name': 'Registro no Exitoso de Cliente',
                'verbose_name_plural': 'Registros no Exitosos de Clientes',
                'db_table': 'bot_log_incidencias',
                'ordering': ['fechaSuceso'],
            },
        ),
        migrations.AlterField(
            model_name='notificacionusuarios_tel',
            name='registro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot_telegram.registrobotincidencias', verbose_name='registro log asociado'),
        ),
        migrations.DeleteModel(
            name='registroNoExitosoCliente',
        ),
    ]
